### ISSUE TITLE
ECPublicKey import error

### ISSUE THREAD

**Issue by nblum37** [jonasroussel/jsonwebtoken#10]
Hi,

when importing any public PEM key (including the example)
<img width="552" alt="Bildschirmfoto 2021-05-21 um 17 21 20" src="https://user-images.githubusercontent.com/82163574/119161081-317c0880-ba59-11eb-9bde-9f92bf0b55c0.png">,

I run into the following exception:
<img width="1407" alt="Bildschirmfoto 2021-05-21 um 17 20 33" src="https://user-images.githubusercontent.com/82163574/119161063-2e811800-ba59-11eb-9111-f77ebd8b49d4.png">

Not sure, whether I made any mistake.

BR

**Comment by jonasroussel** [comment]
Hi,

I don't know why, this probably come from `pointycastle` library that I used.

Can you paste your PEM here ? I will investigate the problem.

**Comment by nblum37** [comment]
It was the PEM from your example [https://github.com/jonasroussel/jsonwebtoken/blob/master/example/ec_public.pem](url)

-----BEGIN PUBLIC KEY-----MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEVs/o5+uQbTjL3chynL4wXgUg2R9q9UU8I5mEovUf86QZ7kOBIjJwqnzD1omageEHWwHdBO6B+dFabmdT9POxg==
-----END PUBLIC KEY-----

Thanks :)

**Comment by jonasroussel** [comment]
Ok,

It was just a little change in `pointycastle` v3.0.1 that I didn't notice.

I published a new version (v2.1.1) that now works !

**Comment by nblum37** [comment]
Thank you!
