### ISSUE TITLE
null-safety

### ISSUE THREAD

**Issue by radvansky-tomas** [jonasroussel/jsonwebtoken#5]
Any plans for migrating to null-safety ?

**Comment by jonasroussel** [comment]
Yes, this is my next milestone.
I'm working on something else currently, but I think I will publish a pre-release for null-safety at the end or march.

**Comment by jonasroussel** [comment]
I had time today to migrating to null-safety.
I published a new version (2.0.0-nullsafety.1), currently in prerelease.
When [pointycastle (https://pub.dev/packages/pointycastle) will be stable and potential bugs fixed, I will publish his stable version (2.0.0).
